apiVersion: v1
kind: Service
metadata:
  name: product-search-service
spec:
  type: ClusterIP   # ← NodePort에서 변경
  selector:
    app: product-search
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      # nodePort 줄 삭제