apiVersion: v1
kind: Service
metadata:
  name: product-search-service
spec:
  type: ClusterIP      # 내부 통신 전용
  selector:
    app: product-search
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
